import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, collection, getDocs, setDoc, doc, deleteDoc, query, orderBy, updateDoc } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let products=[],editing=null;
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('mn-MN').format(n)+'₮';
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';try{await signInWithEmailAndPassword(auth,$('username').value.trim(),$('password').value)}catch(err){$('loginError').textContent='Нэвтрэх мэдээлэл буруу эсвэл Firebase Authentication идэвхгүй байна.'}};
$('logout').onclick=()=>signOut(auth);onAuthStateChanged(auth,user=>{if(user){$('login').classList.add('hidden');$('panel').classList.remove('hidden');loadAll()}else{$('login').classList.remove('hidden');$('panel').classList.add('hidden')}});
async function loadAll(){await loadProducts();await loadOrders()}
async function loadProducts(){const s=await getDocs(collection(db,'products'));products=s.docs.map(d=>d.data());render()}
function render(){$('count').textContent=products.length+' бараа';$('adminProducts').innerHTML=products.map(p=>`<div class="flex gap-3 items-center border rounded-2xl p-3"><img src="${p.image}" class="w-16 h-16 rounded-xl object-cover"><div class="flex-1 min-w-0"><b class="block truncate">${p.name}</b><span class="text-xs text-slate-500">${p.id} · ${p.category} · ${money(p.price)}</span></div><button onclick="editProduct('${p.id}')" class="px-3 py-2 rounded-xl bg-blue-50 text-blue-600 font-bold">Засах</button><button onclick="deleteProduct('${p.id}')" class="px-3 py-2 rounded-xl bg-red-50 text-red-500 font-bold">Устгах</button></div>`).join('')}
$('productForm').onsubmit=async e=>{e.preventDefault();const p={id:$('pId').value.trim(),name:$('pName').value.trim(),price:Number($('pPrice').value),category:$('pCategory').value,rating:Number($('pRating').value),image:$('pImage').value.trim()};await setDoc(doc(db,'products',p.id),p);editing=null;reset();await loadProducts()};
window.editProduct=id=>{const p=products.find(x=>x.id===id);if(!p)return;editing=id;$('pId').value=p.id;$('pName').value=p.name;$('pPrice').value=p.price;$('pCategory').value=p.category;$('pRating').value=p.rating;$('pImage').value=p.image;$('pId').disabled=true;$('formTitle').textContent='Бараа засах';$('cancelEdit').classList.remove('hidden')};window.deleteProduct=async id=>{if(confirm('Энэ барааг устгах уу?')){await deleteDoc(doc(db,'products',id));await loadProducts()}};$('cancelEdit').onclick=reset;function reset(){editing=null;$('productForm').reset();$('pRating').value=5;$('pId').disabled=false;$('formTitle').textContent='Шинэ бараа нэмэх';$('cancelEdit').classList.add('hidden')}
async function loadOrders(){const s=await getDocs(collection(db,'orders'));const orders=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));$('orders').innerHTML=orders.length?orders.map(o=>`<div class="border rounded-2xl p-4"><div class="flex justify-between gap-3"><b>Захиалга #${o.id.slice(0,7)}</b><span class="text-xs px-2 py-1 rounded-full ${o.status==='done'?'bg-green-50 text-green-600':'bg-pink-50 text-pink-600'}">${o.status||'new'}</span></div><p class="text-sm text-slate-500 mt-1">${new Date(o.createdAt).toLocaleString('mn-MN')}</p><div class="mt-3 text-sm">${(o.items||[]).map(i=>`• ${i.name} × ${i.qty} — ${money(i.price)}`).join('<br>')}</div><b class="block mt-3">Нийт: ${money(o.total||0)}</b><button onclick="completeOrder('${o.id}')" class="mt-3 px-3 py-2 rounded-xl bg-green-50 text-green-700 font-bold">Дууссан</button></div>`).join(''):'<p class="text-slate-500">Одоогоор захиалга алга.</p>'}
window.completeOrder=async id=>{await updateDoc(doc(db,'orders',id),{status:'done'});await loadOrders()};
