import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, collection, getDocs, setDoc, doc, deleteDoc, updateDoc, getDoc } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let products=[],editing=null;const ADMIN_EMAIL='12345678littlebo.local@gmail.com';
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('mn-MN').format(n)+'₮';$('username').value=ADMIN_EMAIL;
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';try{await signInWithEmailAndPassword(auth,$('username').value.trim(),$('password').value)}catch(err){$('loginError').textContent='Нэвтрэх мэдээлэл буруу эсвэл Firebase Authentication идэвхгүй байна.';console.error(err)}};
$('logout').onclick=()=>signOut(auth);onAuthStateChanged(auth,user=>{if(user&&user.email===ADMIN_EMAIL){$('login').classList.add('hidden');$('panel').classList.remove('hidden');loadAll()}else if(user){signOut(auth);$('loginError').textContent='Энэ бүртгэл админ эрхгүй байна.'}else{$('login').classList.remove('hidden');$('panel').classList.add('hidden')}});
async function loadAll(){await loadProducts();await loadBank();await loadOrders();addBankButton();addCustomerButton()}
async function loadProducts(){try{const s=await getDocs(collection(db,'products'));products=s.docs.map(d=>d.data());render()}catch(e){console.error(e);$('adminProducts').innerHTML='<p class="text-red-500">Firestore database холбогдоогүй байна. Firebase Console дээр Firestore үүсгэнэ үү.</p>'}}
function render(){$('count').textContent=products.length+' бараа';$('adminProducts').innerHTML=products.map(p=>`<div class="flex gap-3 items-center border rounded-2xl p-3"><img src="${p.image}" class="w-16 h-16 rounded-xl object-cover"><div class="flex-1 min-w-0"><b class="block truncate">${p.name}</b><span class="text-xs text-slate-500">${p.id} · ${p.category} · ${money(p.price)}</span></div><button onclick="editProduct('${p.id}')" class="px-3 py-2 rounded-xl bg-blue-50 text-blue-600 font-bold">Засах</button><button onclick="deleteProduct('${p.id}')" class="px-3 py-2 rounded-xl bg-red-50 text-red-500 font-bold">Устгах</button></div>`).join('')}
$('productForm').onsubmit=async e=>{e.preventDefault();try{const p={id:$('pId').value.trim(),name:$('pName').value.trim(),price:Number($('pPrice').value),category:$('pCategory').value,rating:Number($('pRating').value),image:$('pImage').value.trim()};await setDoc(doc(db,'products',p.id),p);editing=null;reset();await loadProducts()}catch(err){alert('Бараа хадгалахад алдаа: '+err.message)}};
window.editProduct=id=>{const p=products.find(x=>x.id===id);if(!p)return;editing=id;$('pId').value=p.id;$('pName').value=p.name;$('pPrice').value=p.price;$('pCategory').value=p.category;$('pRating').value=p.rating;$('pImage').value=p.image;$('pId').disabled=true;$('formTitle').textContent='Бараа засах';$('cancelEdit').classList.remove('hidden')};window.deleteProduct=async id=>{if(confirm('Энэ барааг устгах уу?')){await deleteDoc(doc(db,'products',id));await loadProducts()}};$('cancelEdit').onclick=reset;function reset(){editing=null;$('productForm').reset();$('pRating').value=5;$('pId').disabled=false;$('formTitle').textContent='Шинэ бараа нэмэх';$('cancelEdit').classList.add('hidden')}
async function loadBank(){try{const s=await getDoc(doc(db,'settings','bank'));if(s.exists())window.bank=s.data()}catch(e){console.error(e)}}
function bankSettings(){const b=window.bank||{};const bank=prompt('Банкны нэр:',b.bankName||'Хаан банк');if(bank===null)return;const name=prompt('Данс эзэмшигч:',b.accountName||'Батмөнх');if(name===null)return;const number=prompt('Дансны дугаар:',b.accountNumber||'8010878683');if(number===null)return;const desc=prompt('Нэмэлт тайлбар:',b.description||'');setDoc(doc(db,'settings','bank'),{bankName:bank,accountName:name,accountNumber:number,description:desc||''}).then(()=>{window.bank={bankName:bank,accountName:name,accountNumber:number,description:desc||''};alert('Дансны мэдээлэл хадгалагдлаа.')}).catch(e=>alert('Данс хадгалахад алдаа: '+e.message))}
function addBankButton(){const header=document.querySelector('#panel header .flex.gap-2');if(!header||document.getElementById('bankSettingsBtn'))return;const b=document.createElement('button');b.id='bankSettingsBtn';b.className='px-4 py-2 rounded-full bg-amber-50 font-bold';b.textContent='🏦 Данс';b.onclick=bankSettings;header.prepend(b)}
const statusText={pending_payment:'⏳ Төлбөр хүлээгдэж байна',paid:'✅ Төлбөр баталгаажсан',confirmed:'📦 Захиалга баталгаажсан',completed:'🎉 Захиалга дууссан',cancelled:'❌ Цуцлагдсан'};
async function loadOrders(){try{const s=await getDocs(collection(db,'orders'));const orders=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));$('orders').innerHTML=orders.length?orders.map(o=>`<div class="border rounded-2xl p-4"><div class="flex justify-between gap-3"><b>Захиалга #${o.id.slice(0,7)}</b><span class="text-xs px-2 py-1 rounded-full bg-pink-50 text-pink-600">${statusText[o.status]||statusText.pending_payment}</span></div><p class="text-sm text-slate-500 mt-1">${new Date(o.createdAt).toLocaleString('mn-MN')}</p><div class="mt-3 text-sm">${(o.items||[]).map(i=>`• ${i.name} × ${i.qty} — ${money(i.price)}`).join('<br>')}</div><p class="mt-3 text-sm">👤 ${o.customer?.name||'Нэр оруулаагүй'} · 📞 ${o.customer?.phone||'-'}</p><p class="text-sm">📍 ${o.customer?.address||'-'}</p><p class="text-sm font-bold mt-2">Гүйлгээний утга: ${o.payment?.reference||'Оруулаагүй'}</p><b class="block mt-2">Нийт: ${money(o.total||0)}</b><div class="flex flex-wrap gap-2 mt-3"><button onclick="setOrderStatus('${o.id}','paid')" class="px-3 py-2 rounded-xl bg-green-50 text-green-700 font-bold">💚 Төлбөр баталгаажуулах</button><button onclick="setOrderStatus('${o.id}','confirmed')" class="px-3 py-2 rounded-xl bg-blue-50 text-blue-700 font-bold">📦 Баталгаажуулах</button><button onclick="setOrderStatus('${o.id}','completed')" class="px-3 py-2 rounded-xl bg-purple-50 text-purple-700 font-bold">🎉 Дуусгах</button><button onclick="setOrderStatus('${o.id}','cancelled')" class="px-3 py-2 rounded-xl bg-red-50 text-red-600 font-bold">❌ Цуцлах</button></div></div>`).join(''):'<p class="text-slate-500">Одоогоор захиалга алга.</p>'}catch(e){console.error(e);$('orders').innerHTML='<p class="text-red-500">Захиалгыг унших боломжгүй байна. Firestore Rules-ээ шалгана уу.</p>'}}
window.setOrderStatus=async(id,status)=>{try{await updateDoc(doc(db,'orders',id),{status,statusUpdatedAt:new Date().toISOString(),statusUpdatedBy:ADMIN_EMAIL});await loadOrders()}catch(e){alert('Төлөв өөрчлөх боломжгүй байна. Firestore Rules дээр admin-д update эрх өгнө үү.');console.error(e)}};
async function addCustomer(){let id=(prompt('Хэрэглэгчийн ID (ж: BO10001):')||'').trim().toUpperCase();if(!id)return;let name=(prompt('Хэрэглэгчийн нэр:')||'').trim();let code=(prompt('Хэрэглэгчийн нууц код:')||'').trim();if(!code){alert('Код хоосон байж болохгүй.');return}try{await setDoc(doc(db,'customers',id),{name,code,uid:null,createdAt:new Date().toISOString()});alert(`Хэрэглэгч үүслээ.\nID: ${id}\nКод: ${code}`)}catch(e){alert('Хэрэглэгч үүсгэхэд алдаа: '+e.message)}}
function addCustomerButton(){const header=document.querySelector('#panel header .flex.gap-2');if(!header||document.getElementById('customerButton'))return;const b=document.createElement('button');b.id='customerButton';b.className='px-4 py-2 rounded-full bg-blue-50 text-blue-700 font-bold';b.textContent='👤 Хэрэглэгч ID';b.onclick=addCustomer;header.prepend(b)}